version: '3'

services:
  mongo:
    image: mongo:7.0-jammy
    networks:
      - express
    volumes:
      - $PWD/docker/mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - express
    environment:
      MONGODB_HOST: mongodb://express:password@mongo:27017/express
      NODE_ENV: development
    volumes:
      - app-data:/app
    depends_on:
      - mongo

  nginx:
    image: nginx:stable-alpine3.17-slim
    networks:
      - express
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - $PWD/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/logs/nginx
    depends_on:
      - app

networks:
  express:
    driver: bridge

volumes:
  mongo-data:
  app-data:
  nginx-logs:


